service: url-shortener
frameworkVersion: "4"

package:
  individually: true
  patterns:
    - "!node_modules/**"
    - "!.git/**"
    - "!.gitignore"
    - "!README.md"
    - "!.env*"
    - "!coverage/**"
    - "!.nyc_output/**"
    - "!tests/**"

plugins:
  - serverless-esbuild

build:
  esbuild: false

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  logRetentionInDays: 30
  environment:
    STAGE: ${self:provider.stage}
    USER_POOL_CLIENT_ID:
      Fn::GetAtt:
        - userPoolClient
        - ClientId
    USER_POOL_ID:
      Ref: userPool
    URLS_TABLE: ${self:service}-${self:provider.stage}
    ANALYTICS_TABLE: ${self:service}-${self:provider.stage}-analytics
  httpApi:
    metrics: true
    cors: true
    authorizers:
      jwtAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl:
          Fn::GetAtt:
            - userPool
            - ProviderURL
        audience:
          - Ref: userPoolClient
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - cognito-idp:*
          Resource: "*"

functions:
  #users
  register:
    handler: src/routes/users/register.handler
    events:
      - httpApi:
          method: POST
          path: /api/v1/auth/register

  confirmSignUp:
    handler: src/routes/users/confirm.handler
    events:
      - httpApi:
          method: POST
          path: /api/v1/auth/confirm

  login:
    handler: src/routes/users/login.handler
    events:
      - httpApi:
          method: POST
          path: /api/v1/auth/login

  refresh:
    handler: src/routes/users/refresh.handler
    events:
      - httpApi:
          method: POST
          path: /api/v1/auth/refresh

  #URLs
  shortenUrl:
    handler: src/routes/urls/shorten.handler
    environment:
      GOOGLE_CLOUD_TOKEN: ${env:GOOGLE_CLOUD_TOKEN}
    events:
      - httpApi:
          path: /api/v1/shorten
          method: POST
          authorizer:
            name: jwtAuthorizer

  redirect:
    handler: src/routes/urls/redirect.handler
    events:
      - httpApi:
          path: /{shortCode}
          method: GET

  updateFullURL:
    handler: src/routes/urls/update.handler
    environment:
      GOOGLE_CLOUD_TOKEN: ${env:GOOGLE_CLOUD_TOKEN}
    events:
      - httpApi:
          path: /api/v1/{shortCode}
          method: PATCH
          authorizer:
            name: jwtAuthorizer

  listUserURLs:
    handler: src/routes/urls/list.handler
    events:
      - httpApi:
          path: /api/v1/urls
          method: GET
          authorizer:
            name: jwtAuthorizer

  deleteUrl:
    handler: src/routes/urls/delete.handler
    events:
      - httpApi:
          path: /api/v1/{shortCode}
          method: DELETE
          authorizer:
            name: jwtAuthorizer

  #Analytics

  getAnalytics:
    handler: src/routes/analytics/get_analytics.handler
    events:
      - httpApi:
          path: /api/v1/analytics
          method: GET
          authorizer:
            name: jwtAuthorizer

resources: ${file(resources.yml)}
